services:
  - type: web
    name: password-manager
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: /opt/render/project/src/.venv/bin/gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true 